### ISSUE TITLE
Parameter Description unclear

### ISSUE THREAD

**Issue by StefaE** [kilianknoll/DWDForecast#3]
Very nicely done - and very well documented! Thx. Kilian 👍 Will start playing with it! Still very much at the beginning though.

Going through the config file, I've stumbled over two questions:

- SimpleMultiplicationFactor: The provided example doesn't seem to compute: Module Area = 28 * 1 * 1.6 = 44.8; TotalEfficiency = 0.196 * 0.98 = 0.192; SimpleMultiplicationFactor = 0.278 * 44.8 * 0.192 = 2.391 vs. 8.6051; the factor 0.278 seems be embedded in the code however (line 538) and doesn't need be considered here;

> It would also be useful to remark that 0.196 is the datasheet module efficiency.

- TemperatureOffset: doesn't make sense to me ... it's eventually used in mc_weather and given to pvlib modelling; I assume it's meant to reflect that in summer, cells are hotter than ambient? pvlib claims to be in the tradition of Sandia models, which is also the basis of SAM models. SAM is documented [here](https://www.nrel.gov/docs/fy18osti/67399.pdf), which lists in chapter 10.2ff a complete set of temperature models. 

> SAM's table 11 refers to 'Sandia PV Array Performance Model with Module Database', which seems what pvlib implements [here](https://pvlib-python.readthedocs.io/en/stable/api.html?highlight=temperature_model_parameters#pvlib.temperature.TEMPERATURE_MODEL_PARAMETERS); so, probably nothing to be done on the caller side ...

I haven't read up on all of this yet... I just stumbled over those two things when trying to understand what to put in the config file.

Stefan

**Comment by StefaE** [comment]
on an added note: For my configuration, I get for tomorrow, high noon with TemperatureOffset = 0:
> temp_air = TTT = 12.92C and CellTempSim = 17.44, alas an offset of 4.52

The same result btw., as with TemperatureOffset = 15. If I then force a radiation change in the code:
> `self.PandasDF['Rad1wh'] = 0.277778*self.PandasDF.Rad1h*3`
(not the *3 to make tomorrow "sunny"), I get CellTempSim = 26.62, alas an offset vs. TTT of 13.70

Unfortunately, tomorrow will not be sunny ... - so I revert the *3 factor

Stefan

**Comment by kilianknoll** [comment]
Hi StefaE
I just updated the configuration file to better explain SimpleMultiplicationFactor - and also correct the documentation bug around conversion factor from Joule --> Watt
I did not make any changes to the TemperatureOffset since some users were opting to have such a correction factor - others don´t. In case you do not want to use it, please set TemperatureOffset  to zero.
This is why I will be closing this issue - hope you are ok with this
