### ISSUE TITLE
Calculation of SimpleMultiplicationFactor does not add up

### ISSUE THREAD

**Issue by fredlcore** [kilianknoll/DWDForecast#6]
https://github.com/kilianknoll/DWDForecast/blob/645e0ade556083b4fbb57bba8733f881a8896259/configuration.ini#L77

It seems that the coefficient 0.278 is not used in the demo calulation, as the result of 8.605184 is not correct.
The actual code is probably correct because the coefficient appears in the calculation of Rad1wh, but you know the code better to decide if any kind of correction needs to be made.

Thanks by the way for this insightful approach!

**Comment by kilianknoll** [comment]
Sorry for the delayed response.
SimpleMultiplicationFactor is sort of a super rough fallback initially used before calculations  with pvlib
